import json
from dataclasses import dataclass, asdict
from typing import Dict, Any

@dataclass
class Proof:
    """Represents a proof generated by the wallet"""
    claim_type: str
    value: bool
    challenge: str
    timestamp: str
    signature: str = ""
    public_key: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    def to_json(self) -> str:
        return json.dumps(self.to_dict())
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Proof':
        return cls(**data)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'Proof':
        return cls.from_dict(json.loads(json_str))